### ISSUE TITLE
parse cli param error  `--hello-world` 

### ISSUE THREAD

**Issue by leeluolee** [x-orpheus/svrx#82]
**Describe the bug**

wrong use of camel-case when handle the cli param

**To Reproduce**

```js
svrx --hello-world
```

**Expected behavior**

loading plugin `svrx-plugin-hello-world`

**Screenshots**

![image](https://user-images.githubusercontent.com/731333/64251049-2b26bf80-cf4a-11e9-9355-4c9196a1bb65.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 0.0.8

**Additional context**

**Comment by leeluolee** [comment]
![image](https://user-images.githubusercontent.com/731333/64251217-89ec3900-cf4a-11e9-86cb-50b79bd97dd5.png)

`svrx -p hello-world ` also failed , but with another error report

**Comment by xuchaoying** [comment]
The shortcut of launching a plugin `svrx --name` is currently not supported for plugins with dashed name.  

`svrx --hello-world` will be conflict with boolean option with camel name, so we decide that it should be parsed into: 

```json
{
    "helloWorld": true
}
```

Though, `svrx -p hello-world` or `svrx --plugin hello-world` is truly a bug. :cry:  Will be fixed later.
